site_name: geoSiteYamaguchi
site_url: http://140.227.176.133

theme:
  language: ja
  name: material

nav:
- Home: 'index.md'
- geodjango: 'geodjango.md'
- infra: 'infra.md'
- お問い合わせ: 'about.md'


# タブ付きコンテンツ
- pymdownx.tabbed
# スーパーフェンス機能
- pymdownx.superfences
# アラート装飾
- admonition
